import { Roboto } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<AuthProvider>
				<body className={`${roboto.className} antialiased`}>{children}</body>
			</AuthProvider>
		</html>
	);
}
